#environment variables are in .env file i n this directory and must be loaded per the script

version: '3'
services:
  rtsp_simple_server:
    networks:
      - host_net #just associate with the host network
    image: aler9/rtsp-simple-server
  ffmpeg:
    networks:
      - host_net
    image: linuxserver/ffmpeg:arm32v7-latest
    entrypoint: ffmpeg_entrypoint.sh
networks:
  host_net:
    external:
      name: host