#environment variables are in .env file i n this directory and must be loaded per the script

version: '3'
services:
  rtsp_simple_server:
    networks:
      - host_net #just associate with the host network
    image: aler9/rtsp-simple-server
  ffmpeg:
    networks:
      - host_net
    image: trm_ffmpeg
    platform: linux/arm/v6 #workaround for raspberry pi zero automatic platform selection
    entrypoint: ffmpeg_entrypoint.sh
networks:
  host_net:
    external:
      name: host
